version: '3.3'
services:
  postgres:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  domclick-interview:
    image: dmikhailov1/domclick-interview
    container_name: domclick-interview
    ports:
      - "8080:8080"
    depends_on:
      - postgres